let payloadListaLocal=[], payloadListaRemote=[], payloadFiltro='general';
function payloadIp(){return localStorage.getItem('sebas_ip_final_libre');}
function payloadFmt(n){return n>1048576?(n/1048576).toFixed(2)+' MB':(n/1024).toFixed(1)+' KB';}
async function payloadApi(action,extra={}){const f=new FormData();f.append('action',action);f.append('host_ip',payloadIp()||'');Object.entries(extra).forEach(([k,v])=>f.append(k,v));const r=await fetch('api/payload_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message||'Operación fallida.');return d;}
window.payloadsRecargar=async function(){if(!payloadIp()){ps5Notification('ERROR','Conecta una PS4 primero.','fa-wifi');return;}try{const d=await payloadApi('list');payloadListaLocal=d.local;payloadListaRemote=d.remote;payloadsFiltrar(payloadFiltro);}catch(e){ps5Notification('PAYLOAD',e.message,'fa-triangle-exclamation');}};
window.payloadsFiltrar=function(filtro){payloadFiltro=filtro;payloadRenderizar('payload-local-list',payloadListaLocal,'local');payloadRenderizar('payload-remote-list',payloadListaRemote,'remote');};
function payloadGrupo(type){return type==='linux'?'LINUX':(['dns','signin'].includes(type)?'ESPECIALES':'GENERAL');}
function payloadInfo(p){if(p.type==='dns')return{titulo:'Activar DNS para bloquear actualizaciones',detalle:'NanoDNS redirige dominios configurados de PlayStation a 0.0.0.0.'};if(p.type==='signin')return{titulo:'Activar inicio de sesión falso',detalle:'Habilita el inicio de sesión falso en la consola.'};if(p.type==='linux')return{titulo:'Iniciar Linux',detalle:'Lanzador Linux para una configuración compatible.'};return{titulo:p.name,detalle:p.origin==='proyecto'?'Incluido con GoldHEN Manager.':'Añadido por el usuario.'};}
function payloadRenderizar(id,list,source){const el=document.getElementById(id);if(!el)return;const groups=payloadFiltro==='general'?['GENERAL','LINUX','ESPECIALES']:[payloadFiltro==='especial'?'ESPECIALES':payloadFiltro.toUpperCase()];let html='';for(const group of groups){const items=list.filter(p=>payloadGrupo(p.type)===group);if(!items.length)continue;html+=`<h3 class="mt-3 mb-1 text-[8px] font-black tracking-[.25em] text-cyan-300/80">${group}</h3>`;html+=items.map(p=>{const info=payloadInfo(p);const install=source==='local'?`<button onclick="payloadInstalar('${p.name}')" class="shrink-0 px-2 py-2 rounded-lg bg-cyan-500/10 text-cyan-300 text-[8px]">Instalar</button>`:'';return `<div class="p-3 bg-black/30 rounded-xl flex justify-between items-center gap-2"><div class="min-w-0"><b class="block text-[10px] text-white truncate">${info.titulo}</b><span class="block text-[8px] text-violet-300 font-mono truncate">${p.name}</span><span class="block text-[8px] text-gray-500 leading-relaxed">${info.detalle} · ${payloadFmt(p.size)}</span></div><div class="flex shrink-0 gap-1">${install}<button onclick="payloadEnviar('${p.name}','${source}')" class="px-2 py-2 rounded-lg bg-amber-500/15 text-amber-400 text-[8px]"><i class="fa-solid fa-paper-plane"></i> Cargar</button></div></div>`}).join('');}el.innerHTML=html||'<p class="text-[9px] text-gray-500">No hay payloads de esta categoría.</p>';}
window.payloadInstalar=async function(name){if(!confirm(`Instalar ${name} en /data/payloads/ de la PS4 para usarlo después?`))return;try{await payloadApi('install',{name});await payloadsRecargar();ps5Notification('PAYLOAD','Instalado en /data/payloads/.','fa-check');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.payloadEnviar=async function(name,source){if(!confirm(`¿Enviar ${name} al BinLoader de la PS4?`))return;try{const d=await payloadApi('send',{name,source});ps5Notification('PAYLOAD',`Enviado: ${payloadFmt(d.bytes)}.`,'fa-check');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.payloadSubir=async function(e){const file=e.target.files[0];if(!file)return;try{const f=new FormData();f.append('action','upload');f.append('host_ip',payloadIp()||'');f.append('payload',file);const r=await fetch('api/payload_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message);await payloadsRecargar();}catch(err){ps5Notification('ERROR',err.message,'fa-triangle-exclamation');}finally{e.target.value='';}};
