let payloadListaLocal=[], payloadListaRemote=[], payloadFiltro='general';
function payloadIp(){return localStorage.getItem('sebas_ip_final_libre');}function payloadFmt(n){return n>1048576?(n/1048576).toFixed(2)+' MB':(n/1024).toFixed(1)+' KB';}
async function payloadApi(action,extra={}){const f=new FormData();f.append('action',action);f.append('host_ip',payloadIp()||'');Object.entries(extra).forEach(([k,v])=>f.append(k,v));const r=await fetch('api/payload_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message||'Operación fallida.');return d;}
window.payloadsRecargar=async function(){if(!payloadIp()){ps5Notification('ERROR','Conecta una PS4 primero.','fa-wifi');return;}try{const d=await payloadApi('list');payloadListaLocal=d.local;payloadListaRemote=d.remote;payloadsFiltrar(payloadFiltro);}catch(e){ps5Notification('PAYLOAD',e.message,'fa-triangle-exclamation');}};
window.payloadsFiltrar=function(filtro){payloadFiltro=filtro;const permitir=p=>filtro==='linux'?p.type==='linux':filtro==='especial'?['dns','signin'].includes(p.type):p.type==='general';payloadRenderizar('payload-local-list',payloadListaLocal.filter(permitir),'local');payloadRenderizar('payload-remote-list',payloadListaRemote.filter(permitir),'remote');};
function payloadDescripcion(p){if(p.type==='linux')return 'Lanzador Linux · '+p.name.replace('linux-','').replace('.bin','').toUpperCase();if(p.type==='dns')return 'NanoDNS · bloquea dominios definidos';if(p.type==='signin')return 'Inicio de sesión falso';return p.origin==='proyecto'?'Incluido con GoldHen Manager AJ':'Payload guardado por el usuario';}
function payloadRenderizar(id,list,source){const el=document.getElementById(id);el.innerHTML=list.length?'':'<p class="text-[9px] text-gray-500">No hay payloads de esta categoría.</p>';list.forEach(p=>el.insertAdjacentHTML('beforeend',`<div class="p-3 bg-black/30 rounded-xl flex justify-between items-center gap-2"><div class="min-w-0"><b class="block text-[10px] text-white truncate">${p.name}</b><span class="block text-[8px] text-gray-500">${payloadDescripcion(p)} · ${payloadFmt(p.size)}</span></div><button onclick="payloadEnviar('${p.name}','${source}')" class="shrink-0 px-3 py-2 rounded-lg bg-amber-500/15 text-amber-400 text-[9px]"><i class="fa-solid fa-paper-plane"></i> Cargar</button></div>`));}
window.payloadEnviar=async function(name,source){if(!confirm(`¿Enviar ${name} al BinLoader de la PS4?`))return;try{const d=await payloadApi('send',{name,source});ps5Notification('PAYLOAD',`Enviado: ${payloadFmt(d.bytes)}.`,'fa-check');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.payloadSubir=async function(e){const file=e.target.files[0];if(!file)return;try{const f=new FormData();f.append('action','upload');f.append('host_ip',payloadIp()||'');f.append('payload',file);const r=await fetch('api/payload_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message);await payloadsRecargar();}catch(err){ps5Notification('ERROR',err.message,'fa-triangle-exclamation');}finally{e.target.value='';}};
