let pluginsLocales = [], pluginsRemotos = [], pluginsIni = { default: [] };
const pluginsCatalogo = {
  'afr.prx': ['Control avanzado de FPS', 'Módulo técnico Advanced Frame Rate para gestionar o modificar los FPS de juegos compatibles.'],
  'aio_fix_505.prx': ['Corrección para firmware 5.05', 'All-In-One Fix para compatibilidad en firmware 5.05; normalmente no es necesario en versiones superiores.'],
  'button_swap.prx': ['Intercambiar botones', 'Invierte los botones principales de confirmación y cancelación, como X y Círculo.'],
  'fliprate_remover.prx': ['Eliminar límites de refresco', 'Intenta quitar límites de refresco o FPS impuestos por algunos títulos compatibles.'],
  'force_1080p_display.prx': ['Forzar salida 1080p', 'Fuerza una salida de vídeo a 1080p en pantallas y juegos compatibles.'],
  'force_30_fps.prx': ['Limitar a 30 FPS', 'Limita el juego a 30 FPS para priorizar una experiencia más estable.'],
  'frame_logger.prx': ['Registro de fotogramas', 'Herramienta técnica que registra o monitoriza el rendimiento de los FPS.'],
  'gamepad_helper.prx': ['Asistente de mandos', 'Ayuda a mejorar la compatibilidad de mandos o controladores alternativos.'],
  'game_patch.prx': ['Parches de juego', 'Aplica parches o correcciones generales durante la ejecución de los juegos.'],
  'gtav_60fps.prx': ['GTA V a 60 FPS', 'Parche específico para desbloquear o forzar 60 FPS en Grand Theft Auto V.'],
  'LSOPlugin.prx': ['LSO Plugin', 'Plugin adicional LSO. Consulta su documentación antes de asignarlo.'],
  'no_share_watermark.prx': ['Quitar marca de Share', 'Oculta la marca de agua y avisos molestos al realizar capturas o vídeos.'],
  'plugin_loader.prx': ['Cargador secundario de plugins', 'Inicializa y administra plugins adicionales con extensión .prx.'],
  'plugin_template.prx': ['Plantilla para desarrolladores', 'Estructura base para desarrollar plugins propios; es un plugin técnico.'],
  'yt_adblock.prx': ['Bloqueador de anuncios de YouTube', 'Bloquea anuncios en la aplicación de YouTube de la consola.']
};
function pluginsIp() { return localStorage.getItem('sebas_ip_final_libre'); }
function pluginsEscape(v) { const d=document.createElement('div'); d.textContent=String(v||''); return d.innerHTML; }
function pluginsInfo(name) { const p=pluginsCatalogo[name]; return p ? {titulo:p[0], detalle:p[1]} : {titulo:'Plugin personalizado', detalle:'Plugin .prx personalizado. Verifica su compatibilidad antes de activarlo.'}; }
function pluginsFD(action) { const f=new FormData(); f.append('action', action); f.append('host_ip', pluginsIp()||''); return f; }
async function pluginsPeticion(action, extra={}) { const f=pluginsFD(action); Object.entries(extra).forEach(([k,v])=>f.append(k,v)); const r=await fetch('api/plugins_api.php',{method:'POST',body:f}); const d=await r.json(); if(d.status!=='success') throw new Error(d.message||'Operación fallida.'); return d; }
function pluginsJuegos() { return typeof listadoJuegos !== 'undefined' && Array.isArray(listadoJuegos) ? listadoJuegos.slice().sort((a,b)=>(a.nombre||a.id).localeCompare(b.nombre||b.id)) : []; }
function pluginsDestinoActual() { return document.getElementById('plugins-section')?.value || 'default'; }
function pluginsActualizarCabecera() { const section=pluginsDestinoActual(), juego=pluginsJuegos().find(j=>j.id===section), cover=document.getElementById('plugins-target-cover'), name=document.getElementById('plugins-target-name'), id=document.getElementById('plugins-target-id'); if(!cover||!name||!id)return; if(!juego){cover.innerHTML='<i class="fa-solid fa-globe"></i>';cover.style.backgroundImage='';name.textContent='Entorno general';id.textContent='[default] · Plugins activos en todo el sistema';return;} const imagen=juego.cover3d||juego.img||''; cover.innerHTML=imagen?`<img src="${pluginsEscape(imagen)}" class="w-full h-full object-cover" onerror="this.remove()">`:'<i class="fa-solid fa-gamepad"></i>'; name.textContent=juego.nombre||juego.id; id.textContent=`[${juego.id}] · Asignación específica`; }
window.pluginsRecargar=async function(){ if(!pluginsIp()){ps5Notification('ERROR','Conecta una PS4 primero.','fa-wifi');return;} try { if((typeof listadoJuegos==='undefined'||listadoJuegos.length===0)&&typeof levantarCacheLocalBiblioteca==='function') await levantarCacheLocalBiblioteca(); const [l,r,i]=await Promise.all([pluginsPeticion('list_local'),pluginsPeticion('list_remote'),pluginsPeticion('get_ini')]); pluginsLocales=l.data||[];pluginsRemotos=r.data||[];pluginsIni=i.sections||{default:[]};pluginsActualizarCabecera();pluginsRenderizar(); } catch(e){ps5Notification('PLUGINS',e.message,'fa-triangle-exclamation');} };
window.pluginsAbrirSelector=function(){ const m=document.getElementById('plugins-selector-modal'); if(!m)return; m.classList.remove('hidden');m.classList.add('flex'); const input=document.getElementById('plugins-game-search');if(input)input.value='';pluginsRenderizarSelector(); };
window.pluginsCerrarSelector=function(){const m=document.getElementById('plugins-selector-modal');if(m){m.classList.add('hidden');m.classList.remove('flex');}};
window.pluginsRenderizarSelector=function(){const cont=document.getElementById('plugins-game-list');if(!cont)return;const q=(document.getElementById('plugins-game-search')?.value||'').toLowerCase();const juegos=pluginsJuegos().filter(j=>`${j.id} ${j.nombre||''}`.toLowerCase().includes(q));let html=`<button onclick="pluginsSeleccionarDestino('default')" class="p-3 rounded-xl bg-black/30 text-left flex gap-3 items-center"><span class="w-10 h-10 rounded-lg bg-violet-500/15 flex items-center justify-center text-violet-300"><i class="fa-solid fa-globe"></i></span><span><b class="block text-[10px] text-white">Entorno general</b><small class="text-[8px] text-gray-500">[default] · toda la consola</small></span></button>`; html+=juegos.map(j=>{const img=pluginsEscape(j.cover3d||j.img||'');return `<button onclick="pluginsSeleccionarDestino('${j.id}')" class="p-2 rounded-xl bg-black/30 text-left flex gap-3 items-center"><span class="w-11 h-11 rounded-lg overflow-hidden bg-white/5 flex items-center justify-center">${img?`<img src="${img}" class="w-full h-full object-cover" onerror="this.remove()">`:'<i class="fa-solid fa-gamepad text-gray-500"></i>'}</span><span class="min-w-0"><b class="block text-[10px] text-white truncate">${pluginsEscape(j.nombre||j.id)}</b><small class="text-[8px] text-gray-500 font-mono">[${j.id}]</small></span></button>`;}).join('');cont.innerHTML=html||'<p class="text-[9px] text-gray-500">No hay aplicaciones en la biblioteca todavía.</p>';};
window.pluginsSeleccionarDestino=function(section){const input=document.getElementById('plugins-section');if(!input)return;input.value=section;pluginsCerrarSelector();pluginsActualizarCabecera();pluginsRenderizar();};
function pluginsTarjeta(p, activo, remoto) { const info=pluginsInfo(p.name), boton=remoto?`<button onclick="pluginsAsignar('${p.name}',${!activo})" class="shrink-0 text-[9px] px-3 py-2 rounded-lg ${activo?'bg-emerald-500/20 text-emerald-400':'bg-white/5 text-gray-300'}">${activo?'Activo · quitar':'Activar'}</button>`:`<button onclick="pluginsInstalar('${p.name}')" class="shrink-0 text-[9px] px-3 py-2 rounded-lg ${pluginsRemotos.some(x=>x.name===p.name)?'bg-emerald-500/10 text-emerald-400':'bg-violet-500/20 text-violet-300'}">${pluginsRemotos.some(x=>x.name===p.name)?'En PS4':'Subir'}</button>`;return `<div class="p-3 rounded-xl bg-black/30 flex justify-between items-center gap-3"><div class="min-w-0"><b class="block text-[10px] text-white truncate">${pluginsEscape(info.titulo)}</b><span class="block text-[8px] text-violet-300 font-mono truncate">${pluginsEscape(p.name)}</span><span class="block text-[8px] text-gray-500 leading-relaxed">${pluginsEscape(info.detalle)}</span></div>${boton}</div>`; }
window.pluginsRenderizar=function(){const section=pluginsDestinoActual(), asignados=new Set(pluginsIni[section]||[]), local=document.getElementById('plugins-local-list'),remote=document.getElementById('plugins-remote-list');if(!local||!remote)return;remote.innerHTML=pluginsRemotos.length?pluginsRemotos.map(p=>pluginsTarjeta(p,asignados.has('/data/GoldHEN/plugins/'+p.name),true)).join(''):'<p class="text-[9px] text-gray-500">No se detectaron plugins instalados en PS4.</p>';local.innerHTML=pluginsLocales.length?pluginsLocales.map(p=>pluginsTarjeta(p,false,false)).join(''):'<p class="text-[9px] text-gray-500">No hay .prx en el teléfono ni en el proyecto.</p>';const count=document.getElementById('plugins-remote-count');if(count)count.textContent=pluginsRemotos.length;};
window.pluginsInstalar=async function(name){try{await pluginsPeticion('upload_plugin',{name});await pluginsRecargar();ps5Notification('PLUGINS','Plugin subido a la PS4.','fa-check');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.pluginsAsignar=async function(name,enabled){try{const d=await pluginsPeticion('update_ini',{name,enabled:String(enabled),section:pluginsDestinoActual()});pluginsIni=d.sections||pluginsIni;pluginsRenderizar();ps5Notification('PLUGINS',enabled?'Plugin activado. Reinicia GoldHEN.':'Plugin desactivado. Reinicia GoldHEN.','fa-plug');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.pluginsSubir=async function(e){const file=e.target.files[0];if(!file)return;try{const f=pluginsFD('upload_local');f.append('plugin',file);const r=await fetch('api/plugins_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message);await pluginsRecargar();}catch(err){ps5Notification('ERROR',err.message,'fa-triangle-exclamation');}finally{e.target.value='';}};
