let pluginsLocales = [], pluginsRemotos = [], pluginsIni = { default: [] };
const pluginsDescripcion = { 'afr.prx':'Control técnico avanzado de FPS.', 'button_swap.prx':'Intercambia botones de confirmación.', 'fliprate_remover.prx':'Elimina límites de refresco compatibles.', 'force_1080p_display.prx':'Fuerza salida 1080p compatible.', 'force_30_fps.prx':'Limita a 30 FPS para estabilidad.', 'frame_logger.prx':'Registro técnico de fotogramas.', 'gamepad_helper.prx':'Ayuda de compatibilidad de mandos.', 'game_patch.prx':'Aplica parches generales.', 'gtav_60fps.prx':'Parche 60 FPS para GTA V.', 'LSOPlugin.prx':'Plugin LSO.', 'no_share_watermark.prx':'Oculta marcas de Share.', 'yt_adblock.prx':'Bloquea anuncios de YouTube.' };
function pluginsIp() { return localStorage.getItem('sebas_ip_final_libre'); }
function pluginsFD(action) { const f=new FormData(); f.append('action',action); f.append('host_ip',pluginsIp()||''); return f; }
async function pluginsPeticion(action, extra={}) { const f=pluginsFD(action); Object.entries(extra).forEach(([k,v])=>f.append(k,v)); const r=await fetch('api/plugins_api.php',{method:'POST',body:f}); const d=await r.json(); if(d.status!=='success') throw new Error(d.message||'Operación fallida.'); return d; }
window.pluginsRecargar=async function(){ if(!pluginsIp()){ps5Notification('ERROR','Conecta una PS4 primero.','fa-wifi');return;} try{if((typeof listadoJuegos==='undefined'||listadoJuegos.length===0)&&typeof levantarCacheLocalBiblioteca==='function')await levantarCacheLocalBiblioteca();const [l,r,i]=await Promise.all([pluginsPeticion('list_local'),pluginsPeticion('list_remote'),pluginsPeticion('get_ini')]);pluginsLocales=l.data;pluginsRemotos=r.data;pluginsIni=i.sections||{default:[]};pluginsPoblarSecciones();pluginsRenderizar();}catch(e){ps5Notification('PLUGINS',e.message,'fa-triangle-exclamation');} };
function pluginsPoblarSecciones(){const s=document.getElementById('plugins-section');if(!s)return;const actual=s.value;s.innerHTML='<option value="default">[default] — Entorno general</option>';(listadoJuegos||[]).sort((a,b)=>a.nombre.localeCompare(b.nombre)).forEach(j=>s.insertAdjacentHTML('beforeend',`<option value="${j.id}">[${j.id}] ${j.nombre}</option>`));s.value=[...s.options].some(o=>o.value===actual)?actual:'default';}
window.pluginsRenderizar=function(){const section=document.getElementById('plugins-section')?.value||'default';const asignados=new Set(pluginsIni[section]||[]);const local=document.getElementById('plugins-local-list'),remote=document.getElementById('plugins-remote-list');if(!local||!remote)return;local.innerHTML=pluginsLocales.length?'':'<p class="text-[9px] text-gray-500">No hay .prx locales.</p>';pluginsLocales.forEach(p=>{const existe=pluginsRemotos.some(x=>x.name===p.name);local.insertAdjacentHTML('beforeend',`<div class="p-3 rounded-xl bg-black/30 flex justify-between items-center"><div class="min-w-0"><b class="block text-[10px] text-white truncate">${p.name}</b><span class="text-[8px] text-gray-500">${pluginsDescripcion[p.name]||'Plugin personalizado.'}</span></div><button onclick="pluginsInstalar('${p.name}')" class="text-[9px] px-3 py-2 rounded-lg ${existe?'bg-emerald-500/10 text-emerald-400':'bg-violet-500/20 text-violet-300'}">${existe?'Listo':'Subir'}</button></div>`);});remote.innerHTML=pluginsRemotos.length?'':'<p class="text-[9px] text-gray-500">No se detectaron plugins remotos.</p>';pluginsRemotos.forEach(p=>{const ruta='/data/GoldHEN/plugins/'+p.name;const activo=asignados.has(ruta);remote.insertAdjacentHTML('beforeend',`<div class="p-3 rounded-xl bg-black/30 flex justify-between items-center gap-2"><div class="min-w-0"><b class="block text-[10px] text-white truncate">${p.name}</b><span class="text-[8px] text-gray-500">${pluginsDescripcion[p.name]||'Plugin personalizado.'}</span></div><button onclick="pluginsAsignar('${p.name}',${!activo})" class="text-[9px] px-3 py-2 rounded-lg ${activo?'bg-emerald-500/20 text-emerald-400':'bg-white/5 text-gray-400'}">${activo?'Activo':'Añadir'}</button></div>`);});document.getElementById('plugins-remote-count').innerText=pluginsRemotos.length;};
window.pluginsInstalar=async function(name){try{await pluginsPeticion('upload_plugin',{name});await pluginsRecargar();ps5Notification('PLUGINS','Plugin subido a la PS4.','fa-check');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.pluginsAsignar=async function(name,enabled){try{const d=await pluginsPeticion('update_ini',{name,enabled:String(enabled),section:document.getElementById('plugins-section').value});pluginsIni=d.sections;pluginsRenderizar();ps5Notification('PLUGINS',enabled?'Asignación guardada. Reinicia GoldHEN.':'Asignación eliminada. Reinicia GoldHEN.','fa-plug');}catch(e){ps5Notification('ERROR',e.message,'fa-triangle-exclamation');}};
window.pluginsSubir=async function(e){const file=e.target.files[0];if(!file)return;try{const f=pluginsFD('upload_local');f.append('plugin',file);const r=await fetch('api/plugins_api.php',{method:'POST',body:f});const d=await r.json();if(d.status!=='success')throw new Error(d.message);await pluginsRecargar();}catch(err){ps5Notification('ERROR',err.message,'fa-triangle-exclamation');}finally{e.target.value='';}};
