#!/data/data/com.termux/files/usr/bin/bash
# Administrador local de catálogo. Solo agrega paquetes cuya distribución autorices.
set -u
STORE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"; DATA="$STORE_DIR/data"; COVERS="$STORE_DIR/covers"; CATALOG="$DATA/catalogo.json"
mkdir -p "$DATA" "$COVERS"; [ -f "$CATALOG" ] || printf '[]\n' > "$CATALOG"
command -v jq >/dev/null 2>&1 || { pkg install -y jq || exit 1; }
valid_id(){ [[ "$1" =~ ^CUSA[0-9]{5}$ ]]; }; valid_url(){ [[ "$1" =~ ^https?://.+\.pkg([?#].*)?$ ]]; }
pause(){ read -r -p 'Pulsa Enter para continuar…' _; }
listar(){ jq -r '.[] | "\(.id) | \(.titulo) | v\(.version) | \(.peso_gb // "?") GB | \(.servidor)"' "$CATALOG"; pause; }
verificar(){ jq -r '.[] | "\(.id)|\(.enlaces.pkg)"' "$CATALOG" | while IFS='|' read -r id url; do printf '%s: ' "$id"; curl -ILs --max-time 15 -o /dev/null -w 'HTTP %{http_code} · %{size_download} bytes\n' "$url"; done; pause; }
cover(){ local id="$1" path="$2" out="$COVERS/$id.webp"; [ -z "$path" ] && { printf ''; return; }; [ -f "$path" ] || { echo 'No existe la imagen.' >&2; printf ''; return; }; if command -v cwebp >/dev/null 2>&1; then cwebp -quiet -q 80 -resize 400 0 "$path" -o "$out"; elif command -v ffmpeg >/dev/null 2>&1; then ffmpeg -y -loglevel error -i "$path" -vf 'scale=400:400:force_original_aspect_ratio=decrease' -q:v 80 "$out"; else echo 'Instala libwebp o ffmpeg para convertir carátulas.' >&2; printf ''; return; fi; printf 'store/covers/%s.webp' "$id"; }
anadir(){ clear; read -r -p 'CUSA (CUSA12345): ' id; valid_id "$id" || { echo 'CUSA inválido.'; pause; return; }; jq -e --arg id "$id" '.[]|select(.id==$id)' "$CATALOG" >/dev/null && { echo 'Ese CUSA ya existe. Usa modificar.'; pause; return; }; read -r -p 'Título: ' titulo; read -r -p 'Subtítulo: ' subtitulo; read -r -p 'Categoría: ' categoria; read -r -p 'Versión [1.00]: ' version; version="${version:-1.00}"; read -r -p 'Peso aproximado GB (vacío si desconocido): ' peso; read -r -p 'Descripción: ' descripcion; read -r -p 'Crédito/licencia: ' creditos; read -r -p 'Proveedor informativo: ' servidor; read -r -p 'URL PKG directa autorizada: ' pkg; valid_url "$pkg" || { echo 'Solo se admiten URL http(s) directas terminadas en .pkg.'; pause; return; }; read -r -p 'URL update directa (opcional): ' update; [ -z "$update" ] || valid_url "$update" || { echo 'Update inválido.'; pause; return; }; read -r -p 'DLC directos separados por coma (opcional): ' dlcs; read -r -p 'Ruta de carátula PNG/JPG (opcional): ' image; read -r -p 'Confirmo que puedo distribuir estos enlaces (s/N): ' ok; [[ "$ok" =~ ^[sS]$ ]] || { echo 'Cancelado.'; pause; return; }; local cover_url; cover_url="$(cover "$id" "$image")"; local dlc_json='[]'; [ -z "$dlcs" ] || dlc_json="$(printf '%s' "$dlcs" | jq -R 'split(",")|map(gsub("^\\s+|\\s+$";""))')"; local peso_json='null'; [[ "$peso" =~ ^[0-9]+([.][0-9]+)?$ ]] && peso_json="$peso"; jq --arg id "$id" --arg titulo "$titulo" --arg subtitulo "$subtitulo" --arg categoria "$categoria" --arg version "$version" --arg descripcion "$descripcion" --arg creditos "$creditos" --arg servidor "$servidor" --arg pkg "$pkg" --arg update "$update" --arg cover "$cover_url" --argjson peso "$peso_json" --argjson dlc "$dlc_json" '. += [{id:$id,titulo:$titulo,subtitulo:$subtitulo,categoria:$categoria,version:$version,peso_gb:$peso,descripcion:$descripcion,creditos:$creditos,servidor:$servidor,licencia_confirmada:true,enlaces:{pkg:$pkg,update:(if $update=="" then null else $update end),dlc:$dlc},cover:(if $cover=="" then null else $cover end)}] | sort_by(.titulo)' "$CATALOG" > "$CATALOG.tmp" && mv "$CATALOG.tmp" "$CATALOG"; echo 'Guardado.'; pause; }
eliminar(){ listar; read -r -p 'CUSA a eliminar: ' id; read -r -p "Eliminar $id (s/N): " ok; [[ "$ok" =~ ^[sS]$ ]] || return; jq --arg id "$id" 'map(select(.id!=$id))' "$CATALOG" > "$CATALOG.tmp" && mv "$CATALOG.tmp" "$CATALOG"; rm -f "$COVERS/$id.webp"; }
modificar(){ listar; read -r -p 'CUSA a modificar: ' id; local old; old="$(jq -c --arg id "$id" '.[]|select(.id==$id)' "$CATALOG")"; [ -n "$old" ] || { echo 'No encontrado.'; pause; return; }; local titulo version peso descripcion servidor pkg update; titulo="$(jq -r '.titulo' <<<"$old")"; version="$(jq -r '.version' <<<"$old")"; peso="$(jq -r '.peso_gb // ""' <<<"$old")"; descripcion="$(jq -r '.descripcion' <<<"$old")"; servidor="$(jq -r '.servidor' <<<"$old")"; pkg="$(jq -r '.enlaces.pkg' <<<"$old")"; update="$(jq -r '.enlaces.update // ""' <<<"$old")"; read -r -p "Título [$titulo]: " v; titulo="${v:-$titulo}"; read -r -p "Versión [$version]: " v; version="${v:-$version}"; read -r -p "Peso GB [$peso]: " v; peso="${v:-$peso}"; read -r -p "Descripción [$descripcion]: " v; descripcion="${v:-$descripcion}"; read -r -p "Proveedor [$servidor]: " v; servidor="${v:-$servidor}"; read -r -p "URL PKG [$pkg]: " v; pkg="${v:-$pkg}"; valid_url "$pkg" || { echo 'URL PKG inválida.'; pause; return; }; read -r -p "URL update [$update]: " v; update="${v:-$update}"; [ -z "$update" ] || valid_url "$update" || { echo 'Update inválido.'; pause; return; }; local peso_json='null'; [[ "$peso" =~ ^[0-9]+([.][0-9]+)?$ ]] && peso_json="$peso"; jq --arg id "$id" --arg titulo "$titulo" --arg version "$version" --arg descripcion "$descripcion" --arg servidor "$servidor" --arg pkg "$pkg" --arg update "$update" --argjson peso "$peso_json" 'map(if .id==$id then .titulo=$titulo|.version=$version|.peso_gb=$peso|.descripcion=$descripcion|.servidor=$servidor|.enlaces.pkg=$pkg|.enlaces.update=(if $update=="" then null else $update end) else . end)' "$CATALOG" > "$CATALOG.tmp" && mv "$CATALOG.tmp" "$CATALOG"; echo 'Actualizado.'; pause; }
while :; do clear; printf 'GoldHen Store AJ · Administrador\n\n1) Listar  2) Añadir  3) Modificar  4) Eliminar  5) Verificar enlaces  6) Salir\n'; read -r -p 'Opción: ' opt; case "$opt" in 1)listar;;2)anadir;;3)modificar;;4)eliminar;;5)verificar;;6)exit 0;;*)echo 'Opción inválida.';pause;;esac; done
