<?php $catalogo=@json_decode(@file_get_contents(__DIR__.'/data/catalogo.json'),true) ?: []; ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoldHen Store AJ</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#060913] text-white p-4"><main class="mx-auto max-w-5xl"><header class="mb-6 flex items-center justify-between"><div><h1 class="text-xl font-black">GoldHen Store AJ</h1><p class="text-xs text-cyan-300">Catálogo privado · contenido autorizado</p></div><button onclick="cargarCatalogo()" class="rounded-xl bg-cyan-500/15 px-4 py-2 text-xs text-cyan-200">↻ Actualizar</button></header><p class="mb-4 text-xs text-gray-400">Envía enlaces PKG directos al instalador compatible de tu PS4. No descarga ni almacena paquetes en el teléfono.</p><div id="status" class="mb-3 text-xs text-gray-400"></div><section id="catalogo" class="grid grid-cols-2 gap-3 md:grid-cols-4"></section></main>
<script>
const api='../api/store_api.php'; const fmt=n=>n?`${(n/1073741824).toFixed(2)} GB`:'peso no publicado';
async function peticion(action,extra={}){const f=new FormData();f.append('action',action);Object.entries(extra).forEach(([k,v])=>f.append(k,v));const r=await fetch(api,{method:'POST',body:f});return r.json();}
function tarjeta(j){const cover=j.cover?`../${j.cover}`:'';const extras=[j.enlaces?.update?'update':null,...(j.enlaces?.dlc||[]).map((_,i)=>`dlc:${i}`)].filter(Boolean);return `<article class="overflow-hidden rounded-2xl border border-white/10 bg-white/5"><div class="aspect-square bg-black/30">${cover?`<img class="h-full w-full object-cover" src="${cover}" onerror="this.remove()">`:''}</div><div class="p-3"><b class="block text-sm">${j.titulo}</b><small class="text-cyan-300">${j.id} · v${j.version||'1.00'}</small><p class="mt-1 text-xs text-gray-400">${j.descripcion||''}</p><p class="mt-2 text-xs text-gray-300">${j.peso_gb||'?'} GB · ${j.servidor||'Privado'}</p><div class="mt-3 grid gap-2"><button onclick="instalar('${j.id}','pkg',0)" class="rounded-lg bg-cyan-500/20 py-2 text-xs">Instalar paquete</button>${extras.map(x=>{const [k,i]=x.split(':');return `<button onclick="instalar('${j.id}','${k}',${i||0})" class="rounded-lg bg-white/10 py-2 text-xs">Instalar ${k.toUpperCase()}</button>`}).join('')}<button onclick="verificar('${j.id}')" class="text-xs text-gray-400">Verificar enlace</button></div></div></article>`;}
async function cargarCatalogo(){const s=document.getElementById('status'),box=document.getElementById('catalogo');s.textContent='Actualizando catálogo…';try{const d=await peticion('catalog');if(d.status!=='success')throw Error(d.message);box.innerHTML=d.data.length?d.data.map(tarjeta).join(''):'<p class="text-gray-500">No hay elementos publicados.</p>';s.textContent=`${d.data.length} elementos publicados.`;}catch(e){s.textContent=e.message;}}
async function instalar(id,kind,index){const ip=localStorage.getItem('sebas_ip_final_libre')||prompt('IP de PS4/RPI:');if(!ip)return;const port=localStorage.getItem('store_rpi_port')||prompt('Puerto del instalador:', '12800')||'12800';localStorage.setItem('store_rpi_port',port);const d=await peticion('install',{id,kind,index,ip,port});document.getElementById('status').textContent=d.message;}
async function verificar(id){const d=await peticion('check',{id});document.getElementById('status').textContent=`${d.message}${d.size?` (${fmt(d.size)})`:''}`;}
cargarCatalogo();
</script></body></html>
