<div id="layer-plugins" class="app-layer hidden flex-col p-4 h-[100dvh] w-full overflow-hidden bg-[#060913]">
    <div class="flex items-center justify-between shrink-0 mb-4"><div class="flex items-center gap-3"><button onclick="volverAlLauncher()" class="w-10 h-10 rounded-xl bg-white/5 text-gray-300"><i class="fa-solid fa-arrow-left"></i></button><div><h2 class="text-[17px] font-black uppercase text-white">Plugins</h2><p class="text-[8px] text-violet-400 font-mono tracking-widest">GOLDHEN PLUGIN LOADER</p></div></div><button onclick="pluginsRecargar()" class="w-10 h-10 rounded-xl bg-violet-500/10 border border-violet-500/20 text-violet-400"><i class="fa-solid fa-rotate-right"></i></button></div>
    <div class="flex-1 overflow-y-auto hide-scrollbar flex flex-col gap-4 pb-6">
        <div class="bg-[#0a0f1a] border border-white/5 rounded-2xl p-4"><p class="text-[9px] text-gray-400 leading-relaxed">La asignación se actualiza en <b class="text-violet-400">plugins.ini</b>. Solo se toca el plugin y el destino elegidos; se conserva una copia local antes de cada cambio. Reinicia GoldHEN o la consola para aplicarlo.</p></div>
        <div class="bg-[#0a0f1a] border border-white/5 rounded-2xl p-4 flex flex-col gap-3"><span class="text-[9px] uppercase font-black tracking-widest text-gray-400">Aplicación/juego seleccionado</span><input id="plugins-section" type="hidden" value="default"><button type="button" onclick="pluginsAbrirSelector()" class="w-full min-h-16 rounded-xl border border-white/10 bg-black/25 p-2 flex items-center gap-3 text-left"><div id="plugins-target-cover" class="w-12 h-12 rounded-lg bg-violet-500/15 overflow-hidden flex items-center justify-center shrink-0 text-violet-300"><i class="fa-solid fa-globe"></i></div><div class="min-w-0 flex-1"><b id="plugins-target-name" class="block text-[11px] text-white truncate">Entorno general</b><span id="plugins-target-id" class="block text-[8px] text-gray-500 font-mono">[default] · Plugins activos en todo el sistema</span></div><i class="fa-solid fa-chevron-right text-violet-400 text-xs"></i></button></div>
        <div class="bg-[#0a0f1a] border border-white/5 rounded-2xl p-4"><div class="flex justify-between mb-3"><span class="text-[10px] uppercase font-black tracking-widest text-white">Instalados en PS4</span><span id="plugins-remote-count" class="text-[9px] text-gray-500">0</span></div><p class="text-[8px] text-gray-500 mb-2">Activa o desactiva cada plugin para la aplicación/juego seleccionado.</p><div id="plugins-remote-list" class="flex flex-col gap-2"></div></div>
        <div class="bg-[#0a0f1a] border border-white/5 rounded-2xl p-4"><div class="flex justify-between mb-3"><span class="text-[10px] uppercase font-black tracking-widest text-white">En teléfono / GoldHen Manager</span><label class="text-[9px] text-violet-400 cursor-pointer"><i class="fa-solid fa-plus"></i> Añadir PRX<input id="plugins-upload" type="file" accept=".prx" class="hidden" onchange="pluginsSubir(event)"></label></div><div id="plugins-local-list" class="flex flex-col gap-2"></div></div>
    </div>
</div>
<div id="plugins-selector-modal" class="fixed inset-0 z-[10050] hidden items-end sm:items-center justify-center bg-black/70 p-4" onclick="if(event.target===this)pluginsCerrarSelector()"><div class="w-full max-w-lg max-h-[84dvh] rounded-3xl border border-white/10 bg-[#0a0f1a] p-4 shadow-2xl flex flex-col"><div class="flex items-center justify-between mb-3"><div><b class="text-sm text-white">Seleccionar aplicación/juego</b><p class="text-[9px] text-gray-500">El destino determina la sección de plugins.ini.</p></div><button onclick="pluginsCerrarSelector()" class="w-9 h-9 rounded-xl bg-white/5 text-gray-300"><i class="fa-solid fa-xmark"></i></button></div><input id="plugins-game-search" oninput="pluginsRenderizarSelector()" placeholder="Buscar por nombre o CUSA..." class="mb-3 rounded-xl bg-black/30 border border-white/10 px-3 py-3 text-[10px] text-white outline-none"><div id="plugins-game-list" class="grid grid-cols-1 gap-2 overflow-y-auto hide-scrollbar"></div></div></div>
